// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "chunkadapter.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> ChunkAdapterWrap::prototype;
Nan::Persistent<Function> ChunkAdapterWrap::constructor;

// Supported implementations
// CChunkAdapter(CChunkAdapter& const arg0)
// CChunkAdapter(INodeMap* pNodeMap, __int128_t MaxChunkCacheSize)
ChunkAdapterWrap::ChunkAdapterWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_ChunkAdapter(NULL)
{
    // Check constructor arguments
    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CChunkAdapter")))
    {
        // Unwrap object
        ChunkAdapterWrap* arg0_wrap = ObjectWrap::Unwrap<ChunkAdapterWrap>(info[0]->ToObject());
        CChunkAdapter* arg0 = arg0_wrap->GetWrapped();

        // CChunkAdapter(CChunkAdapter& const arg0)
        m_ChunkAdapter = new CChunkAdapter(*arg0);
    }
    else if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "INodeMap")) && info[1]->IsNumber())
    {
        // Unwrap object
        NodeMapWrap* arg0_wrap = ObjectWrap::Unwrap<NodeMapWrap>(info[0]->ToObject());
        INodeMap* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());

        // CChunkAdapter(INodeMap* pNodeMap, __int128_t MaxChunkCacheSize)
        m_ChunkAdapter = new CChunkAdapter(arg0, arg1);
    }
}

ChunkAdapterWrap::~ChunkAdapterWrap()
{
    delete m_ChunkAdapter;
}

NAN_MODULE_INIT(ChunkAdapterWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("ChunkAdapterWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "attachNodeMap", AttachNodeMap);
    Nan::SetPrototypeMethod(tpl, "detachNodeMap", DetachNodeMap);
    Nan::SetPrototypeMethod(tpl, "checkBufferLayout", CheckBufferLayout);
    Nan::SetPrototypeMethod(tpl, "attachBuffer", AttachBuffer);
    Nan::SetPrototypeMethod(tpl, "detachBuffer", DetachBuffer);
    Nan::SetPrototypeMethod(tpl, "updateBuffer", UpdateBuffer);
    Nan::SetPrototypeMethod(tpl, "clearCaches", ClearCaches);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CChunkAdapter").ToLocalChecked(), function);
}

NAN_METHOD(ChunkAdapterWrap::AttachBuffer)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if ((info.Length() == 3) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "unsigned char")) && info[1]->IsNumber() && (info[2]->IsObject() && (pylon_v8::ToGCString(info[2]->ToObject()->GetConstructorName()) == "AttachStatistics_t")))
    {
        // Unwrap object
        unsigned charWrap* arg0_wrap = ObjectWrap::Unwrap<unsigned charWrap>(info[0]->ToObject());
        unsigned char* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());

        // Unwrap object
        AttachStatistics_tWrap* arg2_wrap = ObjectWrap::Unwrap<AttachStatistics_tWrap>(info[2]->ToObject());
        AttachStatistics_t* arg2 = arg2_wrap->GetWrapped();
    }
}

NAN_METHOD(ChunkAdapterWrap::AttachNodeMap)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "INodeMap")))
    {
        // Unwrap object
        NodeMapWrap* arg0_wrap = ObjectWrap::Unwrap<NodeMapWrap>(info[0]->ToObject());
        INodeMap* arg0 = arg0_wrap->GetWrapped();
    }
}

NAN_METHOD(ChunkAdapterWrap::CheckBufferLayout)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "unsigned char")) && info[1]->IsNumber())
    {
        // Unwrap object
        unsigned charWrap* arg0_wrap = ObjectWrap::Unwrap<unsigned charWrap>(info[0]->ToObject());
        unsigned char* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());
    }
}

NAN_METHOD(ChunkAdapterWrap::ClearCaches)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(ChunkAdapterWrap::DetachBuffer)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(ChunkAdapterWrap::DetachNodeMap)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(ChunkAdapterWrap::UpdateBuffer)
{
    ChunkAdapterWrap* wrappedChunkAdapter = ObjectWrap::Unwrap<ChunkAdapterWrap>(info.This());
    CChunkAdapter* chunkAdapter = wrappedChunkAdapter->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "unsigned char")))
    {
        // Unwrap object
        unsigned charWrap* arg0_wrap = ObjectWrap::Unwrap<unsigned charWrap>(info[0]->ToObject());
        unsigned char* arg0 = arg0_wrap->GetWrapped();
    }
}
