// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "chunkadaptergev.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> ChunkAdapterGEVWrap::prototype;
Nan::Persistent<Function> ChunkAdapterGEVWrap::constructor;

// Supported implementations
// CChunkAdapterGEV(CChunkAdapterGEV& const arg0)
// CChunkAdapterGEV(INodeMap* pNodeMap, __int128_t MaxChunkCacheSize)
ChunkAdapterGEVWrap::ChunkAdapterGEVWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_ChunkAdapterGEV(NULL)
{
    // Check constructor arguments
    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CChunkAdapterGEV")))
    {
        // Unwrap object
        ChunkAdapterGEVWrap* arg0_wrap = ObjectWrap::Unwrap<ChunkAdapterGEVWrap>(info[0]->ToObject());
        CChunkAdapterGEV* arg0 = arg0_wrap->GetWrapped();

        // CChunkAdapterGEV(CChunkAdapterGEV& const arg0)
        m_ChunkAdapterGEV = new CChunkAdapterGEV(*arg0);
    }
    else if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "INodeMap")) && info[1]->IsNumber())
    {
        // Unwrap object
        NodeMapWrap* arg0_wrap = ObjectWrap::Unwrap<NodeMapWrap>(info[0]->ToObject());
        INodeMap* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());

        // CChunkAdapterGEV(INodeMap* pNodeMap, __int128_t MaxChunkCacheSize)
        m_ChunkAdapterGEV = new CChunkAdapterGEV(arg0, arg1);
    }
}

ChunkAdapterGEVWrap::~ChunkAdapterGEVWrap()
{
    delete m_ChunkAdapterGEV;
}

NAN_MODULE_INIT(ChunkAdapterGEVWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("ChunkAdapterGEVWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "checkBufferLayout", CheckBufferLayout);
    Nan::SetPrototypeMethod(tpl, "attachBuffer", AttachBuffer);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CChunkAdapterGEV").ToLocalChecked(), function);
}

NAN_METHOD(ChunkAdapterGEVWrap::AttachBuffer)
{
    ChunkAdapterGEVWrap* wrappedChunkAdapterGEV = ObjectWrap::Unwrap<ChunkAdapterGEVWrap>(info.This());
    CChunkAdapterGEV* chunkAdapterGEV = wrappedChunkAdapterGEV->GetWrapped();

    if ((info.Length() == 3) && info[0]->IsString() && info[1]->IsNumber() && (info[2]->IsObject() && (pylon_v8::ToGCString(info[2]->ToObject()->GetConstructorName()) == "AttachStatistics_t")))
    {
        // Convert from string value
        unsigned char* arg0 = static_cast<unsigned char*>(pylon_v8::ToGCString(info[0]->ToString()).c_str());

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());

        // Unwrap object
        AttachStatisticsWrap* arg2_wrap = ObjectWrap::Unwrap<AttachStatisticsWrap>(info[2]->ToObject());
        AttachStatistics_t* arg2 = arg2_wrap->GetWrapped();

        // Call wrapped method
        chunkAdapterGEV->AttachBuffer(arg0, arg1, arg2);
    }
}

NAN_METHOD(ChunkAdapterGEVWrap::CheckBufferLayout)
{
    ChunkAdapterGEVWrap* wrappedChunkAdapterGEV = ObjectWrap::Unwrap<ChunkAdapterGEVWrap>(info.This());
    CChunkAdapterGEV* chunkAdapterGEV = wrappedChunkAdapterGEV->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        unsigned char* arg0 = static_cast<unsigned char*>(pylon_v8::ToGCString(info[0]->ToString()).c_str());

        // Convert from number value
        __int128_t arg1 = static_cast<__int128_t>(info[1]->NumberValue());

        // Call wrapped method
        chunkAdapterGEV->CheckBufferLayout(arg0, arg1);
    }
}
