// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "edisplaynotationclass.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> EDisplayNotationClassWrap::prototype;
Nan::Persistent<Function> EDisplayNotationClassWrap::constructor;

// Supported implementations
// EDisplayNotationClass()
// EDisplayNotationClass(EDisplayNotationClass& const arg0)
EDisplayNotationClassWrap::EDisplayNotationClassWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_EDisplayNotationClass(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // EDisplayNotationClass()
        m_EDisplayNotationClass = new EDisplayNotationClass();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "EDisplayNotationClass")))
    {
        // Unwrap object
        EDisplayNotationClassWrap* arg0_wrap = ObjectWrap::Unwrap<EDisplayNotationClassWrap>(info[0]->ToObject());
        EDisplayNotationClass* arg0 = arg0_wrap->GetWrapped();

        // EDisplayNotationClass(EDisplayNotationClass& const arg0)
        m_EDisplayNotationClass = new EDisplayNotationClass(*arg0);
    }
}

EDisplayNotationClassWrap::~EDisplayNotationClassWrap()
{
    delete m_EDisplayNotationClass;
}

NAN_MODULE_INIT(EDisplayNotationClassWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("EDisplayNotationClassWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "fromString", FromString);
    Nan::SetPrototypeMethod(tpl, "toString", ToString);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("EDisplayNotationClass").ToLocalChecked(), function);
}

NAN_METHOD(EDisplayNotationClassWrap::FromString)
{
    EDisplayNotationClassWrap* wrappedEDisplayNotationClass = ObjectWrap::Unwrap<EDisplayNotationClassWrap>(info.This());
    EDisplayNotationClass* eDisplayNotationClass = wrappedEDisplayNotationClass->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value to pointer
        EDisplayNotation arg1_value = static_cast<EDisplayNotation>(info[1]->NumberValue());
        EDisplayNotation* arg1 = &arg1_value;

        // Call wrapped method
        eDisplayNotationClass->FromString(*arg0, arg1);
    }
}

NAN_METHOD(EDisplayNotationClassWrap::ToString)
{
    EDisplayNotationClassWrap* wrappedEDisplayNotationClass = ObjectWrap::Unwrap<EDisplayNotationClassWrap>(info.This());
    EDisplayNotationClass* eDisplayNotationClass = wrappedEDisplayNotationClass->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value to pointer
        EDisplayNotation arg1_value = static_cast<EDisplayNotation>(info[1]->NumberValue());
        EDisplayNotation* arg1 = &arg1_value;

        // Call wrapped method
        eDisplayNotationClass->ToString(*arg0, arg1);
    }
    else if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        EDisplayNotation arg0 = static_cast<EDisplayNotation>(info[0]->NumberValue());

        // Call wrapped method
        eDisplayNotationClass->ToString(arg0);
    }
}
