// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "eventadapteru3v.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> EventAdapterU3VWrap::prototype;
Nan::Persistent<Function> EventAdapterU3VWrap::constructor;

// Supported implementations
// CEventAdapterU3V(INodeMap* pNodeMap)
// CEventAdapterU3V(CEventAdapterU3V& const arg0)
EventAdapterU3VWrap::EventAdapterU3VWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_EventAdapterU3V(NULL)
{
    // Check constructor arguments
    if (info[0]->IsObject())
    {
        gcstring info0_constructor = pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName());
        if (info0_constructor != "INodeMap")
        {
            ThrowException(Exception::TypeError(String::New("CEventAdapterU3V::CEventAdapterU3V: bad argument")));
        }

        // Unwrap obj
        NodeMapWrap* arg0_wrap = ObjectWrap::Unwrap<NodeMapWrap>(info[0]->ToObject());
        INodeMap* arg0 = arg0_wrap->GetWrapped();

        // CEventAdapterU3V(INodeMap* pNodeMap)
        m_EventAdapterU3V = new CEventAdapterU3V(arg0);
    }
    else if (info[0]->IsObject())
    {
        gcstring info0_constructor = pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName());
        if (info0_constructor != "CEventAdapterU3V")
        {
            ThrowException(Exception::TypeError(String::New("CEventAdapterU3V::CEventAdapterU3V: bad argument")));
        }

        // Unwrap obj
        EventAdapterU3VWrap* arg0_wrap = ObjectWrap::Unwrap<EventAdapterU3VWrap>(info[0]->ToObject());
        CEventAdapterU3V* arg0 = arg0_wrap->GetWrapped();

        // CEventAdapterU3V(CEventAdapterU3V& const arg0)
        m_EventAdapterU3V = new CEventAdapterU3V(*arg0);
    }
}

EventAdapterU3VWrap::~EventAdapterU3VWrap()
{
    delete m_EventAdapterU3V;
}

NAN_MODULE_INIT(EventAdapterU3VWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("EventAdapterU3VWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "deliverMessage", DeliverMessage);
    Nan::SetPrototypeMethod(tpl, "deliverEventMessage", DeliverEventMessage);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CEventAdapterU3V").ToLocalChecked(), function);
}
