// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "gcstring.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> GCStringWrap::prototype;
Nan::Persistent<Function> GCStringWrap::constructor;

// Supported implementations
// gcstring()
// gcstring(char* const pc)
// gcstring(gcstring& const str)
// gcstring(wchar_t* const pBufferUTF16)
// gcstring(char* const pc, unsigned int n)
// gcstring(unsigned int count, char ch)
// gcstring(wchar_t* const pBufferUTF16, unsigned int n)
GCStringWrap::GCStringWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_GCString(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // gcstring()
        m_GCString = new gcstring();
    }
    else if ((info.Length() == 1) && info[0]->IsString())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // gcstring(char* const pc)
        m_GCString = new gcstring(arg0);
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // gcstring(gcstring& const str)
        m_GCString = new gcstring(*arg0);
    }
    else if ((info.Length() == 1) && info[0]->IsString())
    {
        // Convert from string value
        wchar_t* arg0 = static_cast<wchar_t*>(pylon_v8::ToGCString(info[0]->ToString()).w_str());

        // gcstring(wchar_t* const pBufferUTF16)
        m_GCString = new gcstring(arg0);
    }
    else if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // gcstring(char* const pc, unsigned int n)
        m_GCString = new gcstring(arg0, arg1);
    }
    else if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsString())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Convert from string value
        char arg1 = pylon_v8::ToGCString(info[1]->ToString()).c_str()[0];

        // gcstring(unsigned int count, char ch)
        m_GCString = new gcstring(arg0, arg1);
    }
    else if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        wchar_t* arg0 = static_cast<wchar_t*>(pylon_v8::ToGCString(info[0]->ToString()).w_str());

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // gcstring(wchar_t* const pBufferUTF16, unsigned int n)
        m_GCString = new gcstring(arg0, arg1);
    }
}

GCStringWrap::~GCStringWrap()
{
    delete m_GCString;
}

NAN_MODULE_INIT(GCStringWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("GCStringWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "append", append);
    Nan::SetPrototypeMethod(tpl, "assign", assign);
    Nan::SetPrototypeMethod(tpl, "compare", compare);
    Nan::SetPrototypeMethod(tpl, "w_str", w_str);
    Nan::SetPrototypeMethod(tpl, "c_str", c_str);
    Nan::SetPrototypeMethod(tpl, "empty", empty);
    Nan::SetPrototypeMethod(tpl, "find", find);
    Nan::SetPrototypeMethod(tpl, "length", length);
    Nan::SetPrototypeMethod(tpl, "size", size);
    Nan::SetPrototypeMethod(tpl, "resize", resize);
    Nan::SetPrototypeMethod(tpl, "max_size", max_size);
    Nan::SetPrototypeMethod(tpl, "substr", substr);
    Nan::SetPrototypeMethod(tpl, "find_first_of", find_first_of);
    Nan::SetPrototypeMethod(tpl, "find_first_not_of", find_first_not_of);
    Nan::SetPrototypeMethod(tpl, "_npos", _npos);
    Nan::SetPrototypeMethod(tpl, "swap", swap);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("gcstring").ToLocalChecked(), function);

    // Register static functions in Node JS
    Nan::Set(target, Nan::New<String>("throwBadAlloc").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(GCStringWrap::ThrowBadAlloc)).ToLocalChecked());
    Nan::Set(target, Nan::New<String>("getline").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(GCStringWrap::getline)).ToLocalChecked());
}

NAN_METHOD(GCStringWrap::_npos)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        unsigned int result = gCString->_npos();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::append)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsString())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Convert from string value
        char arg1 = pylon_v8::ToGCString(info[1]->ToString()).c_str()[0];

        // Call wrapped method
        gCString->append(arg0, arg1);
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        gCString->append(*arg0);
    }
}

NAN_METHOD(GCStringWrap::assign)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        wchar_t* arg0 = static_cast<wchar_t*>(pylon_v8::ToGCString(info[0]->ToString()).w_str());

        // Convert from number value
        int arg1 = static_cast<int>(info[1]->NumberValue());

        // Call wrapped method
        gCString->assign(arg0, arg1);
    }
    else if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        gCString->assign(arg0, arg1);
    }
    else if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsString())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Convert from string value
        char arg1 = pylon_v8::ToGCString(info[1]->ToString()).c_str()[0];

        // Call wrapped method
        gCString->assign(arg0, arg1);
    }
    else if ((info.Length() == 1) && info[0]->IsString())
    {
        // Convert from string value
        wchar_t* arg0 = static_cast<wchar_t*>(pylon_v8::ToGCString(info[0]->ToString()).w_str());

        // Call wrapped method
        gCString->assign(arg0);
    }
    else if ((info.Length() == 1) && info[0]->IsString())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Call wrapped method
        gCString->assign(arg0);
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        gCString->assign(*arg0);
    }
}

NAN_METHOD(GCStringWrap::c_str)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        const char* result = gCString->c_str();

        // Set return value
        info.GetReturnValue().Set(pylon_v8::FromGCString(result).ToLocalChecked());
    }
}

NAN_METHOD(GCStringWrap::compare)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        int result = gCString->compare(*arg0);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::empty)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        bool result = gCString->empty();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}

NAN_METHOD(GCStringWrap::find)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 3) && info[0]->IsString() && info[1]->IsNumber() && info[2]->IsNumber())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Convert from number value
        unsigned int arg2 = static_cast<unsigned int>(info[2]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find(arg0, arg1, arg2);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
    else if ((info.Length() == 3) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber() && info[2]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Convert from number value
        unsigned int arg2 = static_cast<unsigned int>(info[2]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find(*arg0, arg1, arg2);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
    else if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find(arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
    else if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find(*arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
    else if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        char arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str()[0];

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find(arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::find_first_not_of)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find_first_not_of(*arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::find_first_of)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")) && info[1]->IsNumber())
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        unsigned int result = gCString->find_first_of(*arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::length)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        unsigned int result = gCString->length();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::max_size)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        unsigned int result = gCString->max_size();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::resize)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Call wrapped method
        gCString->resize(arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(GCStringWrap::size)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        unsigned int result = gCString->size();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(GCStringWrap::substr)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsNumber())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Call wrapped method
        gCString->substr(arg0, arg1);
    }
}

NAN_METHOD(GCStringWrap::swap)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // Unwrap object
        GCStringWrap* arg0_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[0]->ToObject());
        gcstring* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        gCString->swap(*arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(GCStringWrap::w_str)
{
    GCStringWrap* wrappedGCString = ObjectWrap::Unwrap<GCStringWrap>(info.This());
    gcstring* gCString = wrappedGCString->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        gCString->w_str();
    }
}

NAN_METHOD(GCStringWrap::getline)
{
    if ((info.Length() == 3) && info[0]->IsObject() && (info[1]->IsObject() && (pylon_v8::ToGCString(info[1]->ToObject()->GetConstructorName()) == "gcstring")) && info[2]->IsString())
    {
        // TODO: Implement wrapper for basic_istream<char, std::char_traits<char> >

        // Unwrap object
        GCStringWrap* arg1_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[1]->ToObject());
        gcstring* arg1 = arg1_wrap->GetWrapped();

        // Convert from string value
        char arg2 = pylon_v8::ToGCString(info[2]->ToString()).c_str()[0];

        // Call wrapped function
        // TODO: Implement return value wrapper for getline(*arg0, *arg1, arg2)
    }
    else if ((info.Length() == 2) && info[0]->IsObject() && (info[1]->IsObject() && (pylon_v8::ToGCString(info[1]->ToObject()->GetConstructorName()) == "gcstring")))
    {
        // TODO: Implement wrapper for basic_istream<char, std::char_traits<char> >

        // Unwrap object
        GCStringWrap* arg1_wrap = ObjectWrap::Unwrap<GCStringWrap>(info[1]->ToObject());
        gcstring* arg1 = arg1_wrap->GetWrapped();

        // Call wrapped function
        // TODO: Implement return value wrapper for getline(*arg0, *arg1)
    }
}

NAN_METHOD(GCStringWrap::ThrowBadAlloc)
{
    if ((info.Length() == 2) && info[0]->IsString() && info[1]->IsNumber())
    {
        // Convert from string value
        char* arg0 = pylon_v8::ToGCString(info[0]->ToString()).c_str();

        // Convert from number value
        int arg1 = static_cast<int>(info[1]->NumberValue());

        // Call wrapped function
        ThrowBadAlloc(arg0, arg1);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}
