// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "genericxmlloaderparams.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> GenericXmlloaderparamsWrap::prototype;
Nan::Persistent<Function> GenericXmlloaderparamsWrap::constructor;

// Supported implementations
// CGeneric_XMLLoaderParams()
// CGeneric_XMLLoaderParams(CGeneric_XMLLoaderParams& const arg0)
GenericXmlloaderparamsWrap::GenericXmlloaderparamsWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_GenericXmlloaderparams(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CGeneric_XMLLoaderParams()
        m_GenericXmlloaderparams = new CGeneric_XMLLoaderParams();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CGeneric_XMLLoaderParams")))
    {
        // Unwrap object
        GenericXmlloaderparamsWrap* arg0_wrap = ObjectWrap::Unwrap<GenericXmlloaderparamsWrap>(info[0]->ToObject());
        CGeneric_XMLLoaderParams* arg0 = arg0_wrap->GetWrapped();

        // CGeneric_XMLLoaderParams(CGeneric_XMLLoaderParams& const arg0)
        m_GenericXmlloaderparams = new CGeneric_XMLLoaderParams(*arg0);
    }
}

GenericXmlloaderparamsWrap::~GenericXmlloaderparamsWrap()
{
    delete m_GenericXmlloaderparams;
}

NAN_MODULE_INIT(GenericXmlloaderparamsWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("GenericXmlloaderparamsWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CGeneric_XMLLoaderParams").ToLocalChecked(), function);

    // Register static functions in Node JS
    Nan::Set(target, Nan::New<String>("castToIDestroy").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(GenericXmlloaderparamsWrap::CastToIDestroy)).ToLocalChecked());
}

NAN_METHOD(GenericXmlloaderparamsWrap::CastToIDestroy)
{
    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "INodeMap")))
    {
        // Unwrap object
        NodeMapWrap* arg0_wrap = ObjectWrap::Unwrap<NodeMapWrap>(info[0]->ToObject());
        INodeMap* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped function
        // TODO: Implement return value wrapper for CastToIDestroy(arg0)
    }
}
