// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "ichunkport.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> ChunkPortWrap::prototype;
Nan::Persistent<Function> ChunkPortWrap::constructor;

// Supported implementations
// IChunkPort()
// IChunkPort(IChunkPort& const arg0)
ChunkPortWrap::ChunkPortWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_ChunkPort(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // IChunkPort()
        m_ChunkPort = new IChunkPort();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "IChunkPort")))
    {
        // Unwrap object
        ChunkPortWrap* arg0_wrap = ObjectWrap::Unwrap<ChunkPortWrap>(info[0]->ToObject());
        IChunkPort* arg0 = arg0_wrap->GetWrapped();

        // IChunkPort(IChunkPort& const arg0)
        m_ChunkPort = new IChunkPort(*arg0);
    }
}

ChunkPortWrap::~ChunkPortWrap()
{
    delete m_ChunkPort;
}

NAN_MODULE_INIT(ChunkPortWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("ChunkPortWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "getChunkID", GetChunkID);
    Nan::SetPrototypeMethod(tpl, "cacheChunkData", CacheChunkData);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("IChunkPort").ToLocalChecked(), function);
}

NAN_METHOD(ChunkPortWrap::CacheChunkData)
{
    ChunkPortWrap* wrappedChunkPort = ObjectWrap::Unwrap<ChunkPortWrap>(info.This());
    IChunkPort* chunkPort = wrappedChunkPort->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        EYesNo result = chunkPort->CacheChunkData();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(ChunkPortWrap::GetChunkID)
{
    ChunkPortWrap* wrappedChunkPort = ObjectWrap::Unwrap<ChunkPortWrap>(info.This());
    IChunkPort* chunkPort = wrappedChunkPort->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        chunkPort->GetChunkID();
    }
}
