// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "integerreft.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> IntegerRefTWrap::prototype;
Nan::Persistent<Function> IntegerRefTWrap::constructor;

// Supported implementations
// CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>()
// CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>(CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>& const arg0)
IntegerRefTWrap::IntegerRefTWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_IntegerRefT(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>()
        m_IntegerRefT = new CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>")))
    {
        // Unwrap object
        IntegerRefTWrap* arg0_wrap = ObjectWrap::Unwrap<IntegerRefTWrap>(info[0]->ToObject());
        CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* arg0 = arg0_wrap->GetWrapped();

        // CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>(CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>& const arg0)
        m_IntegerRefT = new CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>(*arg0);
    }
}

IntegerRefTWrap::~IntegerRefTWrap()
{
    delete m_IntegerRefT;
}

NAN_MODULE_INIT(IntegerRefTWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("IntegerRefTWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "setValue", SetValue);
    Nan::SetPrototypeMethod(tpl, "getValue", GetValue);
    Nan::SetPrototypeMethod(tpl, "getMin", GetMin);
    Nan::SetPrototypeMethod(tpl, "getMax", GetMax);
    Nan::SetPrototypeMethod(tpl, "getIncMode", GetIncMode);
    Nan::SetPrototypeMethod(tpl, "getInc", GetInc);
    Nan::SetPrototypeMethod(tpl, "getListOfValidValues", GetListOfValidValues);
    Nan::SetPrototypeMethod(tpl, "getRepresentation", GetRepresentation);
    Nan::SetPrototypeMethod(tpl, "getUnit", GetUnit);
    Nan::SetPrototypeMethod(tpl, "getFloatAlias", GetFloatAlias);
    Nan::SetPrototypeMethod(tpl, "imposeMin", ImposeMin);
    Nan::SetPrototypeMethod(tpl, "imposeMax", ImposeMax);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>").ToLocalChecked(), function);
}

NAN_METHOD(IntegerRefTWrap::GetFloatAlias)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        integerRefT->GetFloatAlias();
    }
}

NAN_METHOD(IntegerRefTWrap::GetInc)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        __int128_t result = integerRefT->GetInc();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::GetIncMode)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        EIncMode result = integerRefT->GetIncMode();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::GetListOfValidValues)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsBoolean())
    {
        // Convert from boolean value
        bool arg0 = info[0]->BooleanValue();

        // Call wrapped method
        // TODO: Implement return value wrapper for integerRefT->GetListOfValidValues(arg0)
    }
}

NAN_METHOD(IntegerRefTWrap::GetMax)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        __int128_t result = integerRefT->GetMax();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::GetMin)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        __int128_t result = integerRefT->GetMin();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::GetRepresentation)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        ERepresentation result = integerRefT->GetRepresentation();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::GetUnit)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        integerRefT->GetUnit();
    }
}

NAN_METHOD(IntegerRefTWrap::GetValue)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsBoolean() && info[1]->IsBoolean())
    {
        // Convert from boolean value
        bool arg0 = info[0]->BooleanValue();

        // Convert from boolean value
        bool arg1 = info[1]->BooleanValue();

        // Call wrapped method
        __int128_t result = integerRefT->GetValue(arg0, arg1);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Number>(result));
    }
}

NAN_METHOD(IntegerRefTWrap::ImposeMax)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        __int128_t arg0 = static_cast<__int128_t>(info[0]->NumberValue());

        // Call wrapped method
        integerRefT->ImposeMax(arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(IntegerRefTWrap::ImposeMin)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        __int128_t arg0 = static_cast<__int128_t>(info[0]->NumberValue());

        // Call wrapped method
        integerRefT->ImposeMin(arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(IntegerRefTWrap::SetValue)
{
    IntegerRefTWrap* wrappedIntegerRefT = ObjectWrap::Unwrap<IntegerRefTWrap>(info.This());
    CIntegerRefT<GenApi_3_0_Basler_pylon_v5_0::IInteger, GenApi_3_0_Basler_pylon_v5_0::IInteger>* integerRefT = wrappedIntegerRefT->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsBoolean())
    {
        // Convert from number value
        __int128_t arg0 = static_cast<__int128_t>(info[0]->NumberValue());

        // Convert from boolean value
        bool arg1 = info[1]->BooleanValue();

        // Call wrapped method
        integerRefT->SetValue(arg0, arg1);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}
