// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "iselector.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> SelectorWrap::prototype;
Nan::Persistent<Function> SelectorWrap::constructor;

// Supported implementations
// ISelector()
// ISelector(ISelector& const arg0)
SelectorWrap::SelectorWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_Selector(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // ISelector()
        m_Selector = new ISelector();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "ISelector")))
    {
        // Unwrap object
        SelectorWrap* arg0_wrap = ObjectWrap::Unwrap<SelectorWrap>(info[0]->ToObject());
        ISelector* arg0 = arg0_wrap->GetWrapped();

        // ISelector(ISelector& const arg0)
        m_Selector = new ISelector(*arg0);
    }
}

SelectorWrap::~SelectorWrap()
{
    delete m_Selector;
}

NAN_MODULE_INIT(SelectorWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("SelectorWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "isSelector", IsSelector);
    Nan::SetPrototypeMethod(tpl, "getSelectedFeatures", GetSelectedFeatures);
    Nan::SetPrototypeMethod(tpl, "getSelectingFeatures", GetSelectingFeatures);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("ISelector").ToLocalChecked(), function);
}

NAN_METHOD(SelectorWrap::GetSelectedFeatures)
{
    SelectorWrap* wrappedSelector = ObjectWrap::Unwrap<SelectorWrap>(info.This());
    ISelector* selector = wrappedSelector->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "value_vector")))
    {
        // Unwrap object
        ValueVectorWrap* arg0_wrap = ObjectWrap::Unwrap<ValueVectorWrap>(info[0]->ToObject());
        value_vector* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        selector->GetSelectedFeatures(*arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(SelectorWrap::GetSelectingFeatures)
{
    SelectorWrap* wrappedSelector = ObjectWrap::Unwrap<SelectorWrap>(info.This());
    ISelector* selector = wrappedSelector->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "value_vector")))
    {
        // Unwrap object
        ValueVectorWrap* arg0_wrap = ObjectWrap::Unwrap<ValueVectorWrap>(info[0]->ToObject());
        value_vector* arg0 = arg0_wrap->GetWrapped();

        // Call wrapped method
        selector->GetSelectingFeatures(*arg0);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(SelectorWrap::IsSelector)
{
    SelectorWrap* wrappedSelector = ObjectWrap::Unwrap<SelectorWrap>(info.This());
    ISelector* selector = wrappedSelector->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        bool result = selector->IsSelector();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}
