// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "iselectordigit.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace GenApi_3_0_Basler_pylon_v5_0;
using namespace GenICam_3_0_Basler_pylon_v5_0;

Nan::Persistent<FunctionTemplate> SelectorDigitWrap::prototype;
Nan::Persistent<Function> SelectorDigitWrap::constructor;

// Supported implementations
// ISelectorDigit()
// ISelectorDigit(ISelectorDigit& const arg0)
SelectorDigitWrap::SelectorDigitWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_SelectorDigit(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // ISelectorDigit()
        m_SelectorDigit = new ISelectorDigit();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "ISelectorDigit")))
    {
        // Unwrap object
        SelectorDigitWrap* arg0_wrap = ObjectWrap::Unwrap<SelectorDigitWrap>(info[0]->ToObject());
        ISelectorDigit* arg0 = arg0_wrap->GetWrapped();

        // ISelectorDigit(ISelectorDigit& const arg0)
        m_SelectorDigit = new ISelectorDigit(*arg0);
    }
}

SelectorDigitWrap::~SelectorDigitWrap()
{
    delete m_SelectorDigit;
}

NAN_MODULE_INIT(SelectorDigitWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("SelectorDigitWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "setFirst", SetFirst);
    Nan::SetPrototypeMethod(tpl, "setNext", SetNext);
    Nan::SetPrototypeMethod(tpl, "restore", Restore);
    Nan::SetPrototypeMethod(tpl, "toString", ToString);
    Nan::SetPrototypeMethod(tpl, "getSelectorList", GetSelectorList);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("ISelectorDigit").ToLocalChecked(), function);
}

NAN_METHOD(SelectorDigitWrap::GetSelectorList)
{
    SelectorDigitWrap* wrappedSelectorDigit = ObjectWrap::Unwrap<SelectorDigitWrap>(info.This());
    ISelectorDigit* selectorDigit = wrappedSelectorDigit->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "value_vector")) && info[1]->IsBoolean())
    {
        // Unwrap object
        ValueVectorWrap* arg0_wrap = ObjectWrap::Unwrap<ValueVectorWrap>(info[0]->ToObject());
        value_vector* arg0 = arg0_wrap->GetWrapped();

        // Convert from boolean value
        bool arg1 = info[1]->BooleanValue();

        // Call wrapped method
        selectorDigit->GetSelectorList(*arg0, arg1);

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(SelectorDigitWrap::Restore)
{
    SelectorDigitWrap* wrappedSelectorDigit = ObjectWrap::Unwrap<SelectorDigitWrap>(info.This());
    ISelectorDigit* selectorDigit = wrappedSelectorDigit->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        selectorDigit->Restore();

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}

NAN_METHOD(SelectorDigitWrap::SetFirst)
{
    SelectorDigitWrap* wrappedSelectorDigit = ObjectWrap::Unwrap<SelectorDigitWrap>(info.This());
    ISelectorDigit* selectorDigit = wrappedSelectorDigit->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        bool result = selectorDigit->SetFirst();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}

NAN_METHOD(SelectorDigitWrap::SetNext)
{
    SelectorDigitWrap* wrappedSelectorDigit = ObjectWrap::Unwrap<SelectorDigitWrap>(info.This());
    ISelectorDigit* selectorDigit = wrappedSelectorDigit->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsBoolean())
    {
        // Convert from boolean value
        bool arg0 = info[0]->BooleanValue();

        // Call wrapped method
        bool result = selectorDigit->SetNext(arg0);

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}

NAN_METHOD(SelectorDigitWrap::ToString)
{
    SelectorDigitWrap* wrappedSelectorDigit = ObjectWrap::Unwrap<SelectorDigitWrap>(info.This());
    ISelectorDigit* selectorDigit = wrappedSelectorDigit->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        selectorDigit->ToString();
    }
}
