// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "pylon.h"
#include "pylon_v8.h"

#include "pylon/imageformatconverterparams.h"
#include "pylon/instantcameraparams.h"
#include "pylon/acquirecontinuousconfiguration.h"
#include "pylon/acquiresingleframeconfiguration.h"
#include "pylon/cameraeventhandler.h"
#include "pylon/configurationeventhandler.h"
#include "pylon/pylondevice.h"
#include "pylon/deviceaccessmode.h"
#include "pylon/devicefactory.h"
#include "pylon/deviceinfo.h"
#include "pylon/featurepersistence.h"
#include "pylon/grabresultdata.h"
#include "pylon/grabresultptr.h"
#include "pylon/image.h"
#include "pylon/imageeventhandler.h"
#include "pylon/imageformatconverter.h"
#include "pylon/info.h"
#include "pylon/instantcamera.h"
#include "pylon/instantcameraarray.h"
#include "pylon/payloadtype.h"
#include "pylon/pixeltype.h"
#include "pylon/pixelformatconverter.h"
#include "pylon/pylongui.h"
#include "pylon/pylonimage.h"
#include "pylon/pylonimagebase.h"
#include "pylon/result.h"
#include "pylon/reusableimage.h"
#include "pylon/softwaretriggerconfiguration.h"
#include "pylon/streamgrabber.h"
#include "pylon/tlfactory.h"
#include "pylon/transportlayer.h"

using namespace v8;
using namespace Pylon;

NAN_MODULE_INIT(PylonWrap::Initialize)
{
    // Register static functions in Node JS
    Nan::Set(target, Nan::New<String>("pylonInitialize").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(PylonWrap::PylonInitialize)).ToLocalChecked());
    Nan::Set(target, Nan::New<String>("pylonTerminate").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(PylonWrap::PylonTerminate)).ToLocalChecked());
    Nan::Set(target, Nan::New<String>("getPylonVersion").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(PylonWrap::GetPylonVersion)).ToLocalChecked());
    Nan::Set(target, Nan::New<String>("getPylonVersionString").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(PylonWrap::GetPylonVersionString)).ToLocalChecked());

    // Initialize dynamic classes
    ImageformatconverterparamsWrap::Initialize(target);
    InstantcameraparamsWrap::Initialize(target);
    AcquireContinuousConfigurationWrap::Initialize(target);
    AcquireSingleFrameConfigurationWrap::Initialize(target);
    CameraEventHandlerWrap::Initialize(target);
    ConfigurationEventHandlerWrap::Initialize(target);
    PylonDeviceWrap::Initialize(target);
    DeviceaccessmodeWrap::Initialize(target);
    DeviceFactoryWrap::Initialize(target);
    DeviceInfoWrap::Initialize(target);
    FeaturePersistenceWrap::Initialize(target);
    GrabResultDataWrap::Initialize(target);
    GrabResultPtrWrap::Initialize(target);
    ImageWrap::Initialize(target);
    ImageEventHandlerWrap::Initialize(target);
    ImageFormatConverterWrap::Initialize(target);
    InfoBaseWrap::Initialize(target);
    InstantCameraWrap::Initialize(target);
    InstantCameraArrayWrap::Initialize(target);
    PayloadtypeWrap::Initialize(target);
    PixeltypeWrap::Initialize(target);
    PixelFormatConverterWrap::Initialize(target);
    PylonguiWrap::Initialize(target);
    PylonImageWrap::Initialize(target);
    PylonImageBaseWrap::Initialize(target);
    GrabResultWrap::Initialize(target);
    ReusableImageWrap::Initialize(target);
    SoftwareTriggerConfigurationWrap::Initialize(target);
    StreamGrabberWrap::Initialize(target);
    TlFactoryWrap::Initialize(target);
    TransportLayerWrap::Initialize(target);
}

NAN_METHOD(PylonWrap::GetPylonVersion)
{
}

NAN_METHOD(PylonWrap::GetPylonVersionString)
{
}

NAN_METHOD(PylonWrap::PylonInitialize)
{
}

NAN_METHOD(PylonWrap::PylonTerminate)
{
}

NODE_MODULE(pylon, PylonWrap::Initialize)
