// MIT License
// 
// Copyright (c) 2017 - 2018 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "grabresultptr.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace Pylon;

Nan::Persistent<FunctionTemplate> GrabResultPtrWrap::prototype;
Nan::Persistent<Function> GrabResultPtrWrap::constructor;

// Supported implementations
// CGrabResultPtr()
// CGrabResultPtr(CGrabResultPtr& const rhs)
GrabResultPtrWrap::GrabResultPtrWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_GrabResultPtr(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CGrabResultPtr()
        m_GrabResultPtr = new CGrabResultPtr();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CGrabResultPtr")))
    {
        // Unwrap object
        GrabResultPtrWrap* arg0_wrap = ObjectWrap::Unwrap<GrabResultPtrWrap>(info[0]->ToObject());
        CGrabResultPtr* arg0 = arg0_wrap->GetWrapped();

        // CGrabResultPtr(CGrabResultPtr& const rhs)
        m_GrabResultPtr = new CGrabResultPtr(*arg0);
    }
}

GrabResultPtrWrap::~GrabResultPtrWrap()
{
    delete m_GrabResultPtr;
}

NAN_MODULE_INIT(GrabResultPtrWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("GrabResultPtrWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "isValid", IsValid);
    Nan::SetPrototypeMethod(tpl, "release", Release);
    Nan::SetPrototypeMethod(tpl, "isUnique", IsUnique);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CGrabResultPtr").ToLocalChecked(), function);
}

NAN_METHOD(GrabResultPtrWrap::IsUnique)
{
    GrabResultPtrWrap* wrappedGrabResultPtr = ObjectWrap::Unwrap<GrabResultPtrWrap>(info.This());
    CGrabResultPtr* grabResultPtr = wrappedGrabResultPtr->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        bool result = grabResultPtr->IsUnique();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}

NAN_METHOD(GrabResultPtrWrap::IsValid)
{
    GrabResultPtrWrap* wrappedGrabResultPtr = ObjectWrap::Unwrap<GrabResultPtrWrap>(info.This());
    CGrabResultPtr* grabResultPtr = wrappedGrabResultPtr->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        bool result = grabResultPtr->IsValid();

        // Set return value
        info.GetReturnValue().Set(Nan::New<Boolean>(result));
    }
}

NAN_METHOD(GrabResultPtrWrap::Release)
{
    GrabResultPtrWrap* wrappedGrabResultPtr = ObjectWrap::Unwrap<GrabResultPtrWrap>(info.This());
    CGrabResultPtr* grabResultPtr = wrappedGrabResultPtr->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        grabResultPtr->Release();

        // Set return value to undefined
        info.GetReturnValue().SetUndefined();
    }
}
