// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "instantcamera.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace Pylon;

Nan::Persistent<FunctionTemplate> InstantCameraWrap::prototype;
Nan::Persistent<Function> InstantCameraWrap::constructor;

// Supported implementations
// CInstantCamera()
// CInstantCamera(CInstantCamera& const arg0)
// CInstantCamera(IPylonDevice* pDevice, ECleanup cleanupProcedure)
InstantCameraWrap::InstantCameraWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_InstantCamera(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CInstantCamera()
        m_InstantCamera = new CInstantCamera();
    }
    else if (info[0]->IsObject())
    {
        gcstring info0_constructor = pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName());
        if (info0_constructor != "CInstantCamera")
        {
            ThrowException(Exception::TypeError(String::New("CInstantCamera::CInstantCamera: bad argument")));
        }

        // Unwrap obj
        InstantCameraWrap* arg0_wrap = ObjectWrap::Unwrap<InstantCameraWrap>(info[0]->ToObject());
        CInstantCamera* arg0 = arg0_wrap->GetWrapped();

        // CInstantCamera(CInstantCamera& const arg0)
        m_InstantCamera = new CInstantCamera(*arg0);
    }
    else if ((info[0]->IsObject()) && (info[1]->IsNumber()))
    {
        gcstring info0_constructor = pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName());
        if (info0_constructor != "IPylonDevice")
        {
            ThrowException(Exception::TypeError(String::New("CInstantCamera::CInstantCamera: bad argument")));
        }

        // Unwrap obj
        PylonDeviceWrap* arg0_wrap = ObjectWrap::Unwrap<PylonDeviceWrap>(info[0]->ToObject());
        IPylonDevice* arg0 = arg0_wrap->GetWrapped();

        // Convert number value
        ECleanup arg1 = static_cast<ECleanup>(info[1]->NumberValue());

        // CInstantCamera(IPylonDevice* pDevice, ECleanup cleanupProcedure)
        m_InstantCamera = new CInstantCamera(arg0, arg1);
    }
}

InstantCameraWrap::~InstantCameraWrap()
{
    delete m_InstantCamera;
}

NAN_MODULE_INIT(InstantCameraWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("InstantCameraWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "attach", Attach);
    Nan::SetPrototypeMethod(tpl, "isPylonDeviceAttached", IsPylonDeviceAttached);
    Nan::SetPrototypeMethod(tpl, "isCameraDeviceRemoved", IsCameraDeviceRemoved);
    Nan::SetPrototypeMethod(tpl, "hasOwnership", HasOwnership);
    Nan::SetPrototypeMethod(tpl, "destroyDevice", DestroyDevice);
    Nan::SetPrototypeMethod(tpl, "detachDevice", DetachDevice);
    Nan::SetPrototypeMethod(tpl, "open", Open);
    Nan::SetPrototypeMethod(tpl, "isOpen", IsOpen);
    Nan::SetPrototypeMethod(tpl, "close", Close);
    Nan::SetPrototypeMethod(tpl, "startGrabbing", StartGrabbing);
    Nan::SetPrototypeMethod(tpl, "retrieveResult", RetrieveResult);
    Nan::SetPrototypeMethod(tpl, "stopGrabbing", StopGrabbing);
    Nan::SetPrototypeMethod(tpl, "isGrabbing", IsGrabbing);
    Nan::SetPrototypeMethod(tpl, "grabOne", GrabOne);
    Nan::SetPrototypeMethod(tpl, "getQueuedBufferCount", GetQueuedBufferCount);
    Nan::SetPrototypeMethod(tpl, "getGrabResultWaitObject", GetGrabResultWaitObject);
    Nan::SetPrototypeMethod(tpl, "getGrabStopWaitObject", GetGrabStopWaitObject);
    Nan::SetPrototypeMethod(tpl, "getCameraEventWaitObject", GetCameraEventWaitObject);
    Nan::SetPrototypeMethod(tpl, "registerConfiguration", RegisterConfiguration);
    Nan::SetPrototypeMethod(tpl, "deregisterConfiguration", DeregisterConfiguration);
    Nan::SetPrototypeMethod(tpl, "registerImageEventHandler", RegisterImageEventHandler);
    Nan::SetPrototypeMethod(tpl, "deregisterImageEventHandler", DeregisterImageEventHandler);
    Nan::SetPrototypeMethod(tpl, "registerCameraEventHandler", RegisterCameraEventHandler);
    Nan::SetPrototypeMethod(tpl, "deregisterCameraEventHandler", DeregisterCameraEventHandler);
    Nan::SetPrototypeMethod(tpl, "waitForFrameTriggerReady", WaitForFrameTriggerReady);
    Nan::SetPrototypeMethod(tpl, "canWaitForFrameTriggerReady", CanWaitForFrameTriggerReady);
    Nan::SetPrototypeMethod(tpl, "executeSoftwareTrigger", ExecuteSoftwareTrigger);
    Nan::SetPrototypeMethod(tpl, "setCameraContext", SetCameraContext);
    Nan::SetPrototypeMethod(tpl, "getCameraContext", GetCameraContext);
    Nan::SetPrototypeMethod(tpl, "getDeviceInfo", GetDeviceInfo);
    Nan::SetPrototypeMethod(tpl, "getNodeMap", GetNodeMap);
    Nan::SetPrototypeMethod(tpl, "getTLNodeMap", GetTLNodeMap);
    Nan::SetPrototypeMethod(tpl, "getStreamGrabberNodeMap", GetStreamGrabberNodeMap);
    Nan::SetPrototypeMethod(tpl, "getEventGrabberNodeMap", GetEventGrabberNodeMap);
    Nan::SetPrototypeMethod(tpl, "getInstantCameraNodeMap", GetInstantCameraNodeMap);
    Nan::SetPrototypeMethod(tpl, "setBufferFactory", SetBufferFactory);
    Nan::SetPrototypeMethod(tpl, "is1394", Is1394);
    Nan::SetPrototypeMethod(tpl, "isGigE", IsGigE);
    Nan::SetPrototypeMethod(tpl, "isUsb", IsUsb);
    Nan::SetPrototypeMethod(tpl, "isCameraLink", IsCameraLink);
    Nan::SetPrototypeMethod(tpl, "getSfncVersion", GetSfncVersion);
    Nan::SetPrototypeMethod(tpl, "getExtensionInterface", GetExtensionInterface);
    Nan::SetPrototypeMethod(tpl, "isBcon", IsBcon);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CInstantCamera").ToLocalChecked(), function);
}
