// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "instantcameraarray.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace Pylon;

Nan::Persistent<FunctionTemplate> InstantCameraArrayWrap::prototype;
Nan::Persistent<Function> InstantCameraArrayWrap::constructor;

// Supported implementations
// CInstantCameraArray()
// CInstantCameraArray(unsigned int numberOfCameras)
// CInstantCameraArray(CInstantCameraArray& const arg0)
InstantCameraArrayWrap::InstantCameraArrayWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_InstantCameraArray(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CInstantCameraArray()
        m_InstantCameraArray = new CInstantCameraArray();
    }
    else if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // CInstantCameraArray(unsigned int numberOfCameras)
        m_InstantCameraArray = new CInstantCameraArray(arg0);
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CInstantCameraArray")))
    {
        // Unwrap object
        InstantCameraArrayWrap* arg0_wrap = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info[0]->ToObject());
        CInstantCameraArray* arg0 = arg0_wrap->GetWrapped();

        // CInstantCameraArray(CInstantCameraArray& const arg0)
        m_InstantCameraArray = new CInstantCameraArray(*arg0);
    }
}

InstantCameraArrayWrap::~InstantCameraArrayWrap()
{
    delete m_InstantCameraArray;
}

NAN_MODULE_INIT(InstantCameraArrayWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("InstantCameraArrayWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "initialize", Initialize);
    Nan::SetPrototypeMethod(tpl, "isPylonDeviceAttached", IsPylonDeviceAttached);
    Nan::SetPrototypeMethod(tpl, "isCameraDeviceRemoved", IsCameraDeviceRemoved);
    Nan::SetPrototypeMethod(tpl, "destroyDevice", DestroyDevice);
    Nan::SetPrototypeMethod(tpl, "detachDevice", DetachDevice);
    Nan::SetPrototypeMethod(tpl, "open", Open);
    Nan::SetPrototypeMethod(tpl, "isOpen", IsOpen);
    Nan::SetPrototypeMethod(tpl, "close", Close);
    Nan::SetPrototypeMethod(tpl, "getSize", GetSize);
    Nan::SetPrototypeMethod(tpl, "startGrabbing", StartGrabbing);
    Nan::SetPrototypeMethod(tpl, "retrieveResult", RetrieveResult);
    Nan::SetPrototypeMethod(tpl, "stopGrabbing", StopGrabbing);
    Nan::SetPrototypeMethod(tpl, "isGrabbing", IsGrabbing);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CInstantCameraArray").ToLocalChecked(), function);
}

NAN_METHOD(InstantCameraArrayWrap::Close)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::DestroyDevice)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::DetachDevice)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::GetSize)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::Initialize)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());
    }
}

NAN_METHOD(InstantCameraArrayWrap::IsCameraDeviceRemoved)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::IsGrabbing)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::IsOpen)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::IsPylonDeviceAttached)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::Open)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(InstantCameraArrayWrap::RetrieveResult)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if ((info.Length() == 3) && info[0]->IsNumber() && (info[1]->IsObject() && (pylon_v8::ToGCString(info[1]->ToObject()->GetConstructorName()) == "CGrabResultPtr")) && info[2]->IsNumber())
    {
        // Convert from number value
        unsigned int arg0 = static_cast<unsigned int>(info[0]->NumberValue());

        // Unwrap object
        GrabResultPtrWrap* arg1_wrap = ObjectWrap::Unwrap<GrabResultPtrWrap>(info[1]->ToObject());
        CGrabResultPtr* arg1 = arg1_wrap->GetWrapped();

        // Convert from number value
        ETimeoutHandling arg2 = static_cast<ETimeoutHandling>(info[2]->NumberValue());
    }
}

NAN_METHOD(InstantCameraArrayWrap::StartGrabbing)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if ((info.Length() == 2) && info[0]->IsNumber() && info[1]->IsNumber())
    {
        // Convert from number value
        EGrabStrategy arg0 = static_cast<EGrabStrategy>(info[0]->NumberValue());

        // Convert from number value
        EGrabLoop arg1 = static_cast<EGrabLoop>(info[1]->NumberValue());
    }
}

NAN_METHOD(InstantCameraArrayWrap::StopGrabbing)
{
    InstantCameraArrayWrap* wrappedInstantCameraArray = ObjectWrap::Unwrap<InstantCameraArrayWrap>(info.This());
    CInstantCameraArray* instantCameraArray = wrappedInstantCameraArray->GetWrapped();

    if (info.Length() == 0)
    {
    }
}
