// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "pixelformatconverter.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace Pylon;

Nan::Persistent<FunctionTemplate> PixelFormatConverterWrap::prototype;
Nan::Persistent<Function> PixelFormatConverterWrap::constructor;

// Supported implementations
// CPixelFormatConverter()
// CPixelFormatConverter(CPixelFormatConverter& const src)
PixelFormatConverterWrap::PixelFormatConverterWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_PixelFormatConverter(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // CPixelFormatConverter()
        m_PixelFormatConverter = new CPixelFormatConverter();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "CPixelFormatConverter")))
    {
        // Unwrap object
        PixelFormatConverterWrap* arg0_wrap = ObjectWrap::Unwrap<PixelFormatConverterWrap>(info[0]->ToObject());
        CPixelFormatConverter* arg0 = arg0_wrap->GetWrapped();

        // CPixelFormatConverter(CPixelFormatConverter& const src)
        m_PixelFormatConverter = new CPixelFormatConverter(*arg0);
    }
}

PixelFormatConverterWrap::~PixelFormatConverterWrap()
{
    delete m_PixelFormatConverter;
}

NAN_MODULE_INIT(PixelFormatConverterWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("PixelFormatConverterWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "init", Init);
    Nan::SetPrototypeMethod(tpl, "isInitialized", IsInitialized);
    Nan::SetPrototypeMethod(tpl, "convert", Convert);
    Nan::SetPrototypeMethod(tpl, "setOutputBitAlignment", SetOutputBitAlignment);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("CPixelFormatConverter").ToLocalChecked(), function);
}

NAN_METHOD(PixelFormatConverterWrap::Convert)
{
    PixelFormatConverterWrap* wrappedPixelFormatConverter = ObjectWrap::Unwrap<PixelFormatConverterWrap>(info.This());
    CPixelFormatConverter* pixelFormatConverter = wrappedPixelFormatConverter->GetWrapped();

    if ((info.Length() == 6) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "void")) && info[1]->IsNumber() && (info[2]->IsObject() && (pylon_v8::ToGCString(info[2]->ToObject()->GetConstructorName()) == "void")) && info[3]->IsNumber() && (info[4]->IsObject() && (pylon_v8::ToGCString(info[4]->ToObject()->GetConstructorName()) == "SImageFormat")) && (info[5]->IsObject() && (pylon_v8::ToGCString(info[5]->ToObject()->GetConstructorName()) == "SOutputImageFormat")))
    {
        // Unwrap object
        voidWrap* arg0_wrap = ObjectWrap::Unwrap<voidWrap>(info[0]->ToObject());
        void* arg0 = arg0_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg1 = static_cast<unsigned int>(info[1]->NumberValue());

        // Unwrap object
        voidWrap* arg2_wrap = ObjectWrap::Unwrap<voidWrap>(info[2]->ToObject());
        void* arg2 = arg2_wrap->GetWrapped();

        // Convert from number value
        unsigned int arg3 = static_cast<unsigned int>(info[3]->NumberValue());

        // Unwrap object
        SImageFormatWrap* arg4_wrap = ObjectWrap::Unwrap<SImageFormatWrap>(info[4]->ToObject());
        SImageFormat* arg4 = arg4_wrap->GetWrapped();

        // Unwrap object
        SOutputImageFormatWrap* arg5_wrap = ObjectWrap::Unwrap<SOutputImageFormatWrap>(info[5]->ToObject());
        SOutputImageFormat* arg5 = arg5_wrap->GetWrapped();
    }
}

NAN_METHOD(PixelFormatConverterWrap::Init)
{
    PixelFormatConverterWrap* wrappedPixelFormatConverter = ObjectWrap::Unwrap<PixelFormatConverterWrap>(info.This());
    CPixelFormatConverter* pixelFormatConverter = wrappedPixelFormatConverter->GetWrapped();

    if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "SImageFormat")))
    {
        // Unwrap object
        SImageFormatWrap* arg0_wrap = ObjectWrap::Unwrap<SImageFormatWrap>(info[0]->ToObject());
        SImageFormat* arg0 = arg0_wrap->GetWrapped();
    }
}

NAN_METHOD(PixelFormatConverterWrap::IsInitialized)
{
    PixelFormatConverterWrap* wrappedPixelFormatConverter = ObjectWrap::Unwrap<PixelFormatConverterWrap>(info.This());
    CPixelFormatConverter* pixelFormatConverter = wrappedPixelFormatConverter->GetWrapped();

    if (info.Length() == 0)
    {
    }
}

NAN_METHOD(PixelFormatConverterWrap::SetOutputBitAlignment)
{
    PixelFormatConverterWrap* wrappedPixelFormatConverter = ObjectWrap::Unwrap<PixelFormatConverterWrap>(info.This());
    CPixelFormatConverter* pixelFormatConverter = wrappedPixelFormatConverter->GetWrapped();

    if ((info.Length() == 1) && info[0]->IsNumber())
    {
        // Convert from number value
        OutputBitAlignmentEnums arg0 = static_cast<OutputBitAlignmentEnums>(info[0]->NumberValue());
    }
}
