// MIT License
// 
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// ----------------------------------------------------------------------------
// This is auto generated code by pylon-node-gen.
// Do not edit this file or all your changes will be lost after re-generation.
// ----------------------------------------------------------------------------

#include "transportlayer.h"
#include "../pylon_v8.h"

using namespace v8;
using namespace Pylon;

Nan::Persistent<FunctionTemplate> TransportLayerWrap::prototype;
Nan::Persistent<Function> TransportLayerWrap::constructor;

// Supported implementations
// ITransportLayer()
// ITransportLayer(ITransportLayer& const arg0)
TransportLayerWrap::TransportLayerWrap(Nan::NAN_METHOD_ARGS_TYPE info)
  : m_TransportLayer(NULL)
{
    // Check constructor arguments
    if (info.Length() == 0)
    {
        // ITransportLayer()
        m_TransportLayer = new ITransportLayer();
    }
    else if ((info.Length() == 1) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "ITransportLayer")))
    {
        // Unwrap object
        TransportLayerWrap* arg0_wrap = ObjectWrap::Unwrap<TransportLayerWrap>(info[0]->ToObject());
        ITransportLayer* arg0 = arg0_wrap->GetWrapped();

        // ITransportLayer(ITransportLayer& const arg0)
        m_TransportLayer = new ITransportLayer(*arg0);
    }
}

TransportLayerWrap::~TransportLayerWrap()
{
    delete m_TransportLayer;
}

NAN_MODULE_INIT(TransportLayerWrap::Initialize)
{
    // Prepare constructor template
    Local <FunctionTemplate> tpl = Nan::New<FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("TransportLayerWrap").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // Register prototypes to template
    Nan::SetPrototypeMethod(tpl, "getTlInfo", GetTlInfo);
    Nan::SetPrototypeMethod(tpl, "createDeviceInfo", CreateDeviceInfo);
    Nan::SetPrototypeMethod(tpl, "getNodeMap", GetNodeMap);
    Nan::SetPrototypeMethod(tpl, "enumerateInterfaces", EnumerateInterfaces);

    // Register template in Node JS
    prototype.Reset(tpl);
    Local<Function> function = Nan::GetFunction(tpl).ToLocalChecked();
    constructor.Reset(function);
    Nan::Set(target, Nan::New("ITransportLayer").ToLocalChecked(), function);
}

NAN_METHOD(TransportLayerWrap::CreateDeviceInfo)
{
    TransportLayerWrap* wrappedTransportLayer = ObjectWrap::Unwrap<TransportLayerWrap>(info.This());
    ITransportLayer* transportLayer = wrappedTransportLayer->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        transportLayer->CreateDeviceInfo();
    }
}

NAN_METHOD(TransportLayerWrap::EnumerateInterfaces)
{
    TransportLayerWrap* wrappedTransportLayer = ObjectWrap::Unwrap<TransportLayerWrap>(info.This());
    ITransportLayer* transportLayer = wrappedTransportLayer->GetWrapped();

    if ((info.Length() == 2) && (info[0]->IsObject() && (pylon_v8::ToGCString(info[0]->ToObject()->GetConstructorName()) == "InterfaceInfoList")) && info[1]->IsBoolean())
    {
        // Unwrap object
        InterfaceInfoListWrap* arg0_wrap = ObjectWrap::Unwrap<InterfaceInfoListWrap>(info[0]->ToObject());
        InterfaceInfoList* arg0 = arg0_wrap->GetWrapped();

        // Convert from boolean value
        bool arg1 = info[1]->BooleanValue();

        // Call wrapped method
        transportLayer->EnumerateInterfaces(*arg0, arg1);
    }
}

NAN_METHOD(TransportLayerWrap::GetNodeMap)
{
    TransportLayerWrap* wrappedTransportLayer = ObjectWrap::Unwrap<TransportLayerWrap>(info.This());
    ITransportLayer* transportLayer = wrappedTransportLayer->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        transportLayer->GetNodeMap();
    }
}

NAN_METHOD(TransportLayerWrap::GetTlInfo)
{
    TransportLayerWrap* wrappedTransportLayer = ObjectWrap::Unwrap<TransportLayerWrap>(info.This());
    ITransportLayer* transportLayer = wrappedTransportLayer->GetWrapped();

    if (info.Length() == 0)
    {
        // Call wrapped method
        transportLayer->GetTlInfo();
    }
}
