// MIT License
//
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using NodePylonGen.Generator.Generators;
using NodePylonGen.Generator.Model;
using NodePylonGen.Parser.Model;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NodePylonGen.Generator
{
    /// <summary>
    /// Kinds of language generators.
    /// </summary>
    public enum GeneratorType
    {
        NodeJS = 1,
        Java
    }

    /// <summary>
    /// Output generated by each back end generator.
    /// </summary>
    public struct GeneratorOutput
    {
        /// <summary>
        /// Cpp include associated with output.
        /// </summary>
        public TranslationUnit TranslationUnit;

        /// <summary>
        /// Code generators with generated output.
        /// </summary>
        public List<CodeGenerator> Outputs;
    }

    public abstract class Generator
    {
        /// <summary>
        /// Gets the binding context of this generator instance.
        /// </summary>
        public BindingContext Context { get; private set; }

        /// <summary>
        /// Construct an new <see cref="Generator"/> instance. 
        /// </summary>
        protected Generator(BindingContext context)
        {
            Context = context;
        }

        /// <summary>
        /// Called when a translation unit is generated.
        /// </summary>
        public Action<GeneratorOutput> OnUnitGenerated = delegate { };

        /// <summary>
        /// 
        /// </summary>
        public void SetupCodeRules()
        {
            SetupRules();
        }

        /// <summary>
        /// Setup any generator-specific rules here.
        /// </summary>
        protected abstract bool SetupRules();

        /// <summary>
        /// Generate the generator-specific outputs for given context.
        /// </summary>
        protected virtual void Process()
        {
        }

        /// <summary>
        /// Generate the outputs for given context.
        /// </summary>
        public void ProcessCode()
        {
            Context.ApplyRules();
            Process();
        }

        /// <summary>
        /// Generates the outputs for a given translation unit.
        /// </summary>
        protected abstract List<CodeGenerator> Generate(IEnumerable<TranslationUnit> units);

        /// <summary>
        /// Generates the source files
        /// </summary>
        /// <returns></returns>
        public List<GeneratorOutput> GenerateCode()
        {
            List<GeneratorOutput> outputs = new List<GeneratorOutput>();
            List<TranslationUnit> units = Context.TranslationUnitContext.TranslationUnits;

            if (Context.IsJavaGenerator)
            {
                GenerateSingleTemplate(outputs, units);
            }
            else
            {
                GenerateTemplates(outputs, units);
            }
            
            return outputs;
        }

        /// <summary>
        /// Generate templates for output
        /// </summary>
        private void GenerateTemplates(List<GeneratorOutput> outputs, IEnumerable<TranslationUnit> units)
        {
            foreach (TranslationUnit unit in units)
            {
                List<CodeGenerator> templates = Generate(new[] { unit });
                if (templates.Count == 0)
                {
                    return;
                }

                foreach (CodeGenerator template in templates)
                {
                    template.Process();
                }

                GeneratorOutput output = new GeneratorOutput
                {
                    TranslationUnit = unit,
                    Outputs = templates
                };

                outputs.Add(output);
                OnUnitGenerated(output);
            }
        }

        /// <summary>
        /// Generate single template for output
        /// </summary>
        private void GenerateSingleTemplate(List<GeneratorOutput> outputs, IEnumerable<TranslationUnit> units)
        {
            foreach (TranslationUnit unit in units)
            {
                GeneratorOutput output = new GeneratorOutput
                {
                    TranslationUnit = unit,
                    Outputs = Generate(new[] { unit })
                };

                output.Outputs.FirstOrDefault().Process();
                outputs.Add(output);

                OnUnitGenerated(output);
            }
        }
    }
}
