// MIT License
//
// Copyright (c) 2017 Björn Rennfanz <bjoern@fam-rennfanz.de>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using NodePylonGen.Config;
using NodePylonGen.Generator.Model;
using NodePylonGen.Parser.Model;
using System.Collections.Generic;
using System.Linq;

namespace NodePylonGen.Generator
{
    /// <summary>
    /// Kinds of language generators.
    /// </summary>
    public enum GeneratorKind
    {
        NodeJS = 1,
        Java
    }

    /// <summary>
    /// Output generated by each backend generator.
    /// </summary>
    public struct GeneratorOutput
    {
        /// <summary>
        /// Cpp include associated with output.
        /// </summary>
        public CppInclude Include;

        /// <summary>
        /// Code generators with generated output.
        /// </summary>
        public List<CodeGenerator> Outputs;
    }

    public abstract class Generator
    {
        /// <summary>
        /// Gets the binding context of this generator instance.
        /// </summary>
        public BindingContext Context { get; private set; }

        /// <summary>
        /// Construct an new <see cref="Generator"/> instance. 
        /// </summary>
        protected Generator(ConfigMapping config, CppModule mainModule)
        {
            Context = new BindingContext(config, mainModule);
        }

        /// <summary>
        /// Setup any generator-specific passes here.
        /// </summary>
        public abstract bool SetupPasses();

        /// <summary>
        /// Setup any generator-specific processing here.
        /// </summary>
        protected virtual void Process()
        {

        }

        public void ProcessCode()
        {
            Context.RunPasses();
            Process();
        }

        /// <summary>
        /// Generates the outputs for a given translation unit.
        /// </summary>
        protected abstract List<CodeGenerator> Generate(IEnumerable<CppInclude> units);

        /// <summary>
        /// Generates the source files
        /// </summary>
        /// <returns></returns>
        public List<GeneratorOutput> GenerateCode()
        {
            List<GeneratorOutput> outputs = new List<GeneratorOutput>();
            /*
            var units = Context.TranslationUnits.GetGenerated().ToList();

            if (Context.Options.IsCSharpGenerator)
            {
                GenerateSingleTemplate(outputs);
            }
            else
            {
                GenerateTemplates(outputs, units.Where(u => !u.IsSystemHeader));
            }
            */
            return outputs;
        }

    }
}
